version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: nishimura
    main: ./nishimura.go
    binary: nishimura
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w -X github.com/afeldman/Nishimura/cmd.Version={{.Version}}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

